### ISSUE TITLE
Magic_mime.get_extension can use String.rindex?

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-magic-mime#1]
`Magic_mime.get_extension` has a reverse search for a dot. Can it use `String.rindex` instead? http://caml.inria.fr/pub/docs/manual-ocaml/libref/String.html#VALrindex

**Comment by avsm** [comment]
Yep, almost certainly -- I just packaged up ancient code to get it tagged.

**Comment by dsheets** [comment]
Here is what I wrote but it's less efficient due to the check for '.' and '/'. One could also `rindex` twice and maybe the code could get shorter but the present implementation works just fine.

``` ocaml
let get_extension filename =
  let last_i = String.length filename - 1 in
  if last_i < 0 || String.get filename last_i = '/' then ""
  else
    let basename = Filename.basename filename in
    try
      let i = String.rindex basename '.' + 1 in
      String.sub basename i (String.length basename - i)
    with Not_found -> ""
```
