### ISSUE TITLE
Add `text/markdown; charset=utf-8` for `.md` and `.markdown` files

### ISSUE THREAD

**Issue by dbuenzli** [mirage/ocaml-magic-mime#12]
This would allow e.g. http://docs.mirage.io not to download markdown release notes: 

```
 curl --head http://docs.mirage.io/_doc/alcotest/CHANGES.md
HTTP/1.1 200 OK
content-length: 4152
content-type: application/octet-stream
```

The file extensions were taken [from here](https://www.iana.org/assignments/media-types/text/markdown). Note that we should still check that browser do not download the file in this case otherwise I'd suggest to stick to `text/plain; charset=utf-8` until they do.

**Comment by avsm** [comment]
This is almost done in #4 (part of v1.1.0)

however I'm not sure how to add the charset=utf-8 detection, as that is not covered by this library. Is there something available that will give us a reasonable guess at the charset, given the file body?

**Comment by dbuenzli** [comment]
You could read the three first bytes of the file and use [`Uutf.String.encoding_guess`](http://erratique.ch/software/uutf/doc/Uutf.String.html#VALencoding_guess), see [here](http://erratique.ch/software/uutf/doc/Uutf.html#VALdecoder) under "Encoding" for details about the guess.

**Comment by avsm** [comment]
Thanks! That looks like a reasonable solution if no other information is supplied.
