### ISSUE TITLE
non MirageOS backend which depends on libmagic

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-magic-mime#16]
I did a `conf-magic` package some days ago and it should be interesting to use it on `ocaml-magic-mime-unix` for example instead to use our database.

**Comment by dinosaure** [comment]
Anyway, I re-implemented `libmagic` in OCaml (https://github.com/dinosaure/conan).

**Comment by hannesm** [comment]
oh wow, I was not aware of conan. what is the relation to magic-mime? is conan released? should it be part of the mirage organization?

**Comment by dinosaure** [comment]
So the project still is experimental and it is not yet released but it mostly works. I delayed the developpement of it to the next year but the rabbit hole seems enough good to continue the project. I'm ok to move it today in the mirage organization :+1:.
