### ISSUE TITLE
Add mjs to application/javascript

### ISSUE THREAD

**Issue by glondu** [mirage/ocaml-magic-mime#21]
Hello,

Could mjs be added to application/javascript line of mime.types, please?

Cheers,

-- 
Stéphane

**Comment by avsm** [comment]
I don't see .mjs in https://raw.githubusercontent.com/apache/httpd/trunk/docs/conf/mime.types (where we got our base types from), but I've added it manually. It'll be released shortly with https://github.com/mirage/ocaml-magic-mime/pull/22
