### ISSUE TITLE
Please add support for wasm (application/wasm)

### ISSUE THREAD

**Issue by glondu** [mirage/ocaml-magic-mime#27]
This MIME type is required by browsers to run wasm modules.

I suggest to use https://salsa.debian.org/debian/media-types/-/blob/master/mime.types

**Comment by glondu** [comment]
Any news on this?

**Comment by hannesm** [comment]
Thanks. This has been PRed in #28, and is part of the release https://github.com/ocaml/opam-repository/pull/24575

If you submit a PR (instead of an issue) with the proposed changes, this will be much quicker.
