### ISSUE TITLE
Rename to remove 'magic'

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-magic-mime#5]
"Magic" when used in relation to mime types usually implies inspection of file contents (e.g. `file(1)`) rather than simply scraping file names. c.f. http://httpd.apache.org/docs/2.2/mod/mod_mime.html http://httpd.apache.org/docs/2.2/mod/mod_mime_magic.html

Because of this, I believe this library should be renamed to something without "magic" in the name.

**Comment by avsm** [comment]
I actually wanted to extend the library in exactly this direction -- the "magic" means that the library is responsible for guessing the MIME type from available information, and this can include the contents as well as the extension.  The MIME database portion could be split out in the future however...
